server:
  port: 8080

  servlet:
    context-path: /qbrainx-web

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Qbrainx-website
    username: postgres
    password: admin@1234
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true


springdoc:
  group-configs:
    - group: qbrainx-website
      packagesToScan:
        - "com.web"
  swagger-ui:
    path: /qbrainx-1336586310L-swagger-ui.html
  api-docs:
    path: /v3/qbrainx-1336586310L-api-docs
